ABILITIES_ATTRIBUTES = {
    'buffs': {},
    'dmgs': {'d2': {'dmg_category': 'standard_dmg',
                    'dmg_source': 'placeholder',
                    'dmg_type': 'magic',
                    'dmg_values': [40.0, 75.0, 110.0, 145.0, 180.0],
                    'dot': False,
                    'life_conversion_type': 'placeholder',
                    'max_targets': 'placeholder',
                    'mods': {'ap': [0.6]},
                    'radius': 'placeholder',
                    'target_type': 'placeholder'},
             'd3': {'dmg_category': 'placeholder',
                    'dmg_source': 'placeholder',
                    'dmg_type': 'physical',
                    'dmg_values': 1.0,
                    'dot': False,
                    'life_conversion_type': 'placeholder',
                    'max_targets': 'placeholder',
                    'mods': {'bonus_ad': [0.5]},
                    'radius': 'placeholder',
                    'target_type': 'placeholder'},
             'd4': {'dmg_category': 'placeholder',
                    'dmg_source': 'placeholder',
                    'dmg_type': 'magic',
                    'dmg_values': [100.0, 160.0, 220.0],
                    'dot': False,
                    'life_conversion_type': 'placeholder',
                    'max_targets': 'placeholder',
                    'mods': {'ap': [0.7]},
                    'radius': 'placeholder',
                    'target_type': 'placeholder'},
             'dmg_1': {'dmg_category': 'placeholder',
                       'dmg_source': 'placeholder',
                       'dmg_type': 'physical',
                       'dmg_values': [70.0, 110.0, 150.0, 190.0, 230.0],
                       'dot': False,
                       'life_conversion_type': 'placeholder',
                       'max_targets': 'placeholder',
                       'mods': {'ap': [0.6], 'bonus_ad': [1.0]},
                       'radius': 'placeholder',
                       'target_type': 'placeholder'}},
    'general_attributes': {'e': {'base_cd': [16.0, 14.0, 12.0, 10.0, 8.0],
                                 'cost': {'cost_category': 'mana',
                                          'resource_type': 'mp',
                                          'values': (70, 75, 80, 85, 90)},
                                 'range': 0},
                           'inn': {},
                           'q': {'base_cd': [10.0, 9.0, 8.0, 7.0, 6.0],
                                 'cost': {'cost_category': 'mana',
                                          'resource_type': 'mp',
                                          'values': (65, 65, 65, 65, 65)},
                                 'range': 700},
                           'r': {'base_cd': 80.0,
                                 'cost': {'cost_category': 'mana',
                                          'resource_type': 'mp',
                                          'values': (100, 100, 100)},
                                 'range': 0},
                           'w': {'base_cd': [7.0, 6.0, 5.0, 4.0, 3.0],
                                 'cost': {'cost_category': 'mana',
                                          'resource_type': 'mp',
                                          'values': (30, 30, 30, 30, 30)},
                                 'range': 0}}
}

ABILITIES_EFFECTS = {
    'e': {'enemy': {'actives': {'buffs': [], 'dmg': [], 'remove_buff': []},
                    'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}},
          'player': {'actives': {'buffs': [],
                                 'cds_modified': {},
                                 'dmg': [],
                                 'remove_buff': []},
                     'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}}},
    'q': {'enemy': {'actives': {'buffs': [], 'dmg': [], 'remove_buff': []},
                    'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}},
          'player': {'actives': {'buffs': [],
                                 'cds_modified': {},
                                 'dmg': [],
                                 'remove_buff': []},
                     'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}}},
    'r': {'enemy': {'actives': {'buffs': [], 'dmg': [], 'remove_buff': []},
                    'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}},
          'player': {'actives': {'buffs': [],
                                 'cds_modified': {},
                                 'dmg': [],
                                 'remove_buff': []},
                     'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}}},
    'w': {'enemy': {'actives': {'buffs': [], 'dmg': [], 'remove_buff': []},
                    'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}},
          'player': {'actives': {'buffs': [],
                                 'cds_modified': {},
                                 'dmg': [],
                                 'remove_buff': []},
                     'passives': {'buffs': [], 'dmg': [], 'remove_buff': []}}}
}