ABILITIES_ATTRIBUTES = {
    'buffs': {'e_stun_buff': {'buff_source': 'e',
                              'dot': False,
                              'duration': 1.5,
                              'max_stacks': 1,
                              'on_hit': {},
                              'prohibit_cd_start': None,
                              'stats': None,
                              'target_type': 'enemy'},
              'q_buff_0': {'buff_source': 'q',
                           'dot': False,
                           'duration': 5,
                           'max_stacks': 1,
                           'on_hit': {'apply_buff': ['q_dmg'],
                                      'cause_dmg': [],
                                      'reduce_cd': {},
                                      'remove_buff': ['q_buff']},
                           'prohibit_cd_start': 'q',
                           'stats': None,
                           'target_type': 'player'},
              'r_buff_0': {'buff_source': 'r',
                           'dot': False,
                           'duration': (8, 10, 12),
                           'max_stacks': 1,
                           'on_hit': {},
                           'prohibit_cd_start': None,
                           'stats': {'ad': {'additive': {'stat_mods': {},
                                                         'stat_values': [30.0,
                                                                         50.0,
                                                                         70.0]}}},
                           'target_type': 'player'},
              'w_counter_buff': {'buff_source': 'w',
                                 'dot': False,
                                 'duration': 3,
                                 'max_stacks': 3,
                                 'on_hit': {'apply_buff': ['placeholder'],
                                            'cause_dmg': ['placeholder'],
                                            'reduce_cd': {},
                                            'remove_buff': ['placeholder']},
                                 'prohibit_cd_start': None,
                                 'stats': None,
                                 'target_type': 'enemy'},
              'w_initiator_buff': {'buff_source': 'w',
                                   'dot': False,
                                   'duration': 'permanent',
                                   'max_stacks': 1,
                                   'on_hit': {'apply_buff': ['w_counter_buff'],
                                              'cause_dmg': [],
                                              'reduce_cd': {},
                                              'remove_buff': []},
                                   'prohibit_cd_start': None,
                                   'stats': None,
                                   'target_type': 'player'}},
    'dmgs': {'e_impact_dmg': {'delay': None,
                              'dmg_category': 'standard_dmg',
                              'dmg_source': 'e',
                              'dmg_type': 'physical',
                              'dmg_values': [45.0, 80.0, 115.0, 150.0, 185.0],
                              'dot': False,
                              'life_conversion_type': 'spellvamp',
                              'max_targets': 1,
                              'mods': {'enemy': {}, 'player': {'bonus_ad': 0.5}},
                              'radius': None,
                              'resource_type': 'hp',
                              'target_type': 'enemy',
                              'usual_max_targets': 1,
                              'crit_type': None},
             'e_stun_dmg': {'delay': 0.1,
                            'dmg_category': 'standard_dmg',
                            'dmg_source': 'e',
                            'dmg_type': 'physical',
                            'dmg_values': [45.0, 80.0, 115.0, 150.0, 185.0],
                            'dot': False,
                            'life_conversion_type': 'spellvamp',
                            'max_targets': 1,
                            'mods': {'enemy': {}, 'player': {'bonus_ad': 0.5}},
                            'radius': None,
                            'resource_type': 'hp',
                            'target_type': 'enemy',
                            'usual_max_targets': 1,
                            'crit_type': None},
             'q_dmg_0': {'delay': None,
                         'dmg_category': 'standard_dmg',
                         'dmg_source': 'q',
                         'dmg_type': 'physical',
                         'dmg_values': [0, 0, 0, 0, 0],
                         'dot': False,
                         'life_conversion_type': 'lifesteal',
                         'max_targets': 1,
                         'mods': {'enemy': {}, 'player': {'bonus_ad': (0.3, 0.35, 0.4, 0.45, 0.5)}},
                         'radius': None,
                         'resource_type': 'hp',
                         'target_type': 'enemy',
                         'usual_max_targets': 1,
                         'crit_type': None},
             'w_dmg_0': {'delay': None,
                         'dmg_category': 'standard_dmg',
                         'dmg_source': 'w',
                         'dmg_type': 'true',
                         'dmg_values': [20.0, 30.0, 40.0, 50.0, 60.0],
                         'dot': False,
                         'life_conversion_type': None,
                         'max_targets': 1,
                         'mods': {'enemy': {'hp': (0.04, 0.05, 0.06, 0.07, 0.08)}, 'player': {}},
                         'radius': None,
                         'resource_type': 'hp',
                         'target_type': 'enemy',
                         'usual_max_targets': 1,
                         'crit_type': None}},
    'general_attributes': {'e': {'base_cd': (20.0, 18.0, 16.0, 14.0, 12.0),
                                 'cast_time': 0.25,
                                 'castable': True,
                                 'channel_time': None,
                                 'cost': {'stack_cost': None,
                                          'standard_cost': {'cost_category': 'normal',
                                                            'resource_type': 'mp',
                                                            'values': (90,
                                                                       90,
                                                                       90,
                                                                       90,
                                                                       90)}},
                                 'dashed_distance': None,
                                 'independent_cast': False,
                                 'move_while_casting': False,
                                 'range': (710, 710, 710, 710, 710),
                                 'reduces_ability_cd': {},
                                 'resets_aa': False,
                                 'toggled': False,
                                 'travel_time': 0.25},
                           'inn': {},
                           'q': {'base_cd': (6.0, 5.0, 4.0, 3.0, 2.0),
                                 'cast_time': 0.25,
                                 'castable': True,
                                 'channel_time': None,
                                 'cost': {'stack_cost': None,
                                          'standard_cost': {'cost_category': 'normal',
                                                            'resource_type': 'mp',
                                                            'values': (30,
                                                                       30,
                                                                       30,
                                                                       30,
                                                                       30)}},
                                 'dashed_distance': 300,
                                 'independent_cast': False,
                                 'move_while_casting': False,
                                 'range': (300, 300, 300, 300, 300),
                                 'reduces_ability_cd': {},
                                 'resets_aa': True,
                                 'toggled': False,
                                 'travel_time': 0},
                           'r': {'base_cd': (100.0, 85.0, 70.0),
                                 'cast_time': 0,
                                 'castable': True,
                                 'channel_time': None,
                                 'cost': {'stack_cost': None,
                                          'standard_cost': {'cost_category': 'normal',
                                                            'resource_type': 'mp',
                                                            'values': (80,
                                                                       80,
                                                                       80)}},
                                 'dashed_distance': None,
                                 'independent_cast': False,
                                 'move_while_casting': True,
                                 'range': 0,
                                 'reduces_ability_cd': {},
                                 'resets_aa': False,
                                 'toggled': False,
                                 'travel_time': 0},
                           'w': {'castable': False}}}
