ITEMS_NON_UNIQUE_STATS_DCT = {
    'abyssal_scepter': {'ap': 70,
                        'mr': 50},
    'aegis_of_the_legion': {'hp': 200,
                            'mr': 20},
    'aether_wisp': {'ap': 30},
    'amplifying_tome': {'ap': 20},
    'ancient_coin': {'mp': 0.25,
                     'mp5': 0.25},
    'archangels_staff': {'ap': 60,
                         'mp': 0.5,
                         'mp5': 0.5},
    'ardent_censer': {'ap': 40,
                      'cdr': 0.1,
                      'mp': 1.0,
                      'mp5': 1.0},
    'athenes_unholy_grail': {'ap': 60,
                             'cdr': 0.2,
                             'mp': 0.5,
                             'mp5': 0.5,
                             'mr': 25},
    'avarice_blade': {'crit_chance': 0.1},
    'b_f_sword': {'ad': 50},
    'banner_of_command': {'ap': 60,
                          'cdr': 0.1,
                          'hp': 200,
                          'mr': 20},
    'banshees_veil': {'hp': 1.0,
                      'hp5': 1.0,
                      'mr': 55},
    'berserkers_greaves': {'att_speed': 0.25},
    'bilgewater_cutlass': {'ad': 25,
                           'lifesteal': 0.08},
    'blade_of_the_ruined_king': {'ad': 25,
                                 'att_speed': 0.4,
                                 'lifesteal': 0.1},
    'blasting_wand': {'ap': 40},
    'boots_of_mobility': {},
    'boots_of_speed': {},
    'boots_of_swiftness': {},
    'brawlers_gloves': {'crit_chance': 0.08},
    'catalyst_the_protector': {'hp': 200,
                               'mp': 300},
    'chain_vest': {'armor': 40},
    'chalice_of_harmony': {'mp': 0.5,
                           'mp5': 0.5,
                           'mr': 25},
    'cloak_of_agility': {'crit_chance': 0.15},
    'cloth_armor': {'armor': 15},
    'crystalline_bracer': {'hp': 0.5,
                           'hp5': 0.5},
    'dagger': {'att_speed': 0.15},
    'deathfire_grasp': {'ap': 120,
                        'cdr': 0.1},
    'dorans_blade': {'ad': 7,
                     'hp': 70,
                     'lifesteal': 0.03},
    'dorans_ring': {'ap': 15,
                    'hp': 60},
    'dorans_shield': {'hp': 80},
    'enchantment_alacrity': {},
    'enchantment_captain': {},
    'enchantment_devourer': {'att_speed': 0.5},
    'enchantment_distortion': {},
    'enchantment_furor': {},
    'enchantment_homeguard': {},
    'enchantment_juggernaut': {'cdr': 0.1,
                               'hp': 500},
    'enchantment_magus': {'ap': 80,
                          'cdr': 0.2},
    'enchantment_warrior': {'ad': 45,
                            'armor': 10,
                            'cdr': 0.1},
    'essence_reaver': {'ad': 80,
                       'cdr': 0.1,
                       'lifesteal': 0.1},
    'face_of_the_mountain': {'cdr': 0.1,
                             'hp': 1.0,
                             'hp5': 1.0},
    'faerie_charm': {'mp': 0.25,
                     'mp5': 0.25},
    'fiendish_codex': {'ap': 30},
    'forbidden_idol': {'mp': 0.5,
                       'mp5': 0.5},
    'frost_queens_claim': {'ap': 50,
                           'cdr': 0.1,
                           'mp': 0.5,
                           'mp5': 0.5},
    'frostfang': {'ap': 10,
                  'mp': 0.5,
                  'mp5': 0.5},
    'frozen_heart': {'armor': 100,
                     'cdr': 0.2,
                     'mp': 400},
    'frozen_mallet': {'ad': 30,
                      'hp': 700},
    'giants_belt': {'hp': 380},
    'glacial_shroud': {'armor': 20,
                       'mp': 250},
    'guardian_angel': {'armor': 50,
                       'mr': 50},
    'guinsoos_rageblade': {'ad': 30,
                           'ap': 40},
    'haunting_guise': {'ap': 25,
                       'hp': 200},
    'hexdrinker': {'ad': 25,
                   'mr': 30},
    'hextech_gunblade': {'ad': 45,
                         'ap': 65,
                         'lifesteal': 0.12},
    'hextech_revolver': {'ap': 40},
    'hunters_machete': {},
    'iceborn_gauntlet': {'ap': 30,
                         'armor': 60,
                         'cdr': 0.1,
                         'mp': 500},
    'infinity_edge': {'ad': 80,
                      'crit_chance': 0.25},
    'ionian_boots_of_lucidity': {},
    'kindlegem': {'hp': 200},
    'last_whisper': {'ad': 40},
    'liandrys_torment': {'ap': 50,
                         'hp': 300},
    'lich_bane': {'ap': 80,
                  'move_speed': 0.05,
                  'mp': 250},
    'locket_of_the_iron_solari': {'cdr': 0.1,
                                  'hp': 400,
                                  'mr': 20},
    'long_sword': {'ad': 10},
    'madreds_razors': {'att_speed': 0.15},
    'manamune': {'ad': 25,
                 'mp': 0.25,
                 'mp5': 0.25},
    'maw_of_malmortius': {'ad': 60,
                          'mr': 40},
    'mejais_soulstealer': {'ap': 20},
    'mercurial_scimitar': {'ad': 80,
                           'mr': 35},
    'mercurys_treads': {'mr': 25},
    'mikaels_crucible': {'cdr': 0.1,
                         'mp': 1.0,
                         'mp5': 1.0,
                         'mr': 40},
    'morellonomicon': {'ap': 80,
                       'cdr': 0.2,
                       'mp': 1.0,
                       'mp5': 1.0},
    'nashors_tooth': {'ap': 60,
                      'att_speed': 0.5},
    'needlessly_large_rod': {'ap': 80},
    'negatron_cloak': {'mr': 45},
    'ninja_tabi': {'armor': 25},
    'nomads_medallion': {'hp': 0.25,
                         'hp5': 0.25,
                         'move_speed': 10,
                         'mp': 0.25,
                         'mp5': 0.25},
    'null_magic_mantle': {'mr': 25},
    'ohmwrecker': {'armor': 50,
                   'cdr': 0.1,
                   'hp': 1.0,
                   'hp5': 1.0},
    'perfect_hex_core': {'ap': 60,
                         'ap_per_lvl': 6,
                         'mp': 500},
    'phage': {'ad': 20,
              'hp': 200},
    'phantom_dancer': {'att_speed': 0.5,
                       'crit_chance': 0.3,
                       'move_speed': 0.05},
    'pickaxe': {'ad': 25},
    'poachers_knife': {},
    'quicksilver_sash': {'mr': 30},
    'rabadons_deathcap': {'ap': 120},
    'randuins_omen': {'armor': 70,
                      'hp': 500},
    'rangers_trailblazer': {},
    'raptor_cloak': {'armor': 30,
                     'hp': 1.0,
                     'hp5': 1.0},
    'ravenous_hydra': {'ad': 75,
                       'hp': 1.0,
                       'hp5': 1.0,
                       'lifesteal': 0.12},
    'recurve_bow': {'att_speed': 0.3},
    'rejuvenation_bead': {'hp': 0.5,
                          'hp5': 0.5},
    'relic_shield': {'hp': 75},
    'righteous_glory': {'hp': 1.0,
                        'hp5': 1.0,
                        'mp': 300},
    'rod_of_ages': {'ap': 60,
                    'hp': 450,
                    'mp': 450},
    'ruby_crystal': {'hp': 150},
    'ruby_sightstone': {'hp': 400},
    'runaans_hurricane': {'att_speed': 0.7},
    'rylais_crystal_scepter': {'ap': 100,
                               'hp': 400},
    'sapphire_crystal': {'mp': 200},
    'seekers_armguard': {'ap': 25,
                         'armor': 30},
    'sheen': {'ap': 25,
              'mp': 200},
    'sightstone': {'hp': 150},
    'skirmishers_sabre': {},
    'sorcerers_shoes': {'flat_magic_penetration': 15},
    'spectres_cowl': {'hp': 200,
                      'mr': 35},
    'spellthiefs_edge': {'ap': 5,
                         'mp': 0.25,
                         'mp5': 0.25},
    'spirit_visage': {'cdr': 0.1,
                      'hp': 1.0,
                      'hp5': 1.0,
                      'mr': 55},
    'stalkers_blade': {},
    'statikk_shiv': {'att_speed': 0.4,
                     'crit_chance': 0.2,
                     'move_speed': 0.06},
    'stinger': {'att_speed': 0.4},
    'sunfire_cape': {'armor': 45,
                     'hp': 450},
    'sword_of_the_occult': {'ad': 10},
    'talisman_of_ascension': {'cdr': 0.1,
                              'hp': 1.0,
                              'hp5': 1.0,
                              'move_speed': 20,
                              'mp': 1.0,
                              'mp5': 1.0},
    'targons_brace': {'hp': 0.5,
                      'hp5': 0.5},
    'tear_of_the_goddess': {'mp': 0.25,
                            'mp5': 0.25},
    'the_black_cleaver': {'ad': 50,
                          'cdr': 0.1,
                          'hp': 200},
    'the_black_spear': {},
    'the_bloodthirster': {'ad': 80},
    'the_brutalizer': {'ad': 25},
    'the_hex_core_mk_1': {'ap': 20,
                          'ap_per_lvl': 4,
                          'mp': 150},
    'the_hex_core_mk_2': {'ap': 40,
                          'ap_per_lvl': 5,
                          'mp': 300},
    'thornmail': {'armor': 100},
    'tiamat': {'ad': 40,
               'hp': 1.0,
               'hp5': 1.0},
    'trinity_force': {'ad': 30,
                      'ap': 30,
                      'att_speed': 0.3,
                      'crit_chance': 0.1,
                      'hp': 250,
                      'move_speed': 0.08,
                      'mp': 200},
    'twin_shadows': {'ap': 80,
                     'cdr': 0.1,
                     'move_speed': 0.06},
    'vampiric_scepter': {'ad': 10,
                         'lifesteal': 0.08},
    'void_staff': {'ap': 70},
    'wardens_mail': {'armor': 45},
    'warmogs_armor': {'hp': 800},
    'will_of_the_ancients': {'ap': 80,
                             'cdr': 0.1},
    'wits_end': {'att_speed': 0.5,
                 'mr': 30},
    'wriggles_lantern': {'ad': 12,
                         'att_speed': 0.3},
    'youmuus_ghostblade': {'ad': 30,
                           'cdr': 0.1,
                           'crit_chance': 0.15},
    'zeal': {'att_speed': 0.2,
             'crit_chance': 0.1,
             'move_speed': 0.05},
    'zekes_herald': {'cdr': 0.2,
                     'hp': 250},
    'zephyr': {'ad': 25,
               'att_speed': 0.5,
               'cdr': 0.1,
               'move_speed': 0.1},
    'zhonyas_hourglass': {'ap': 120,
                          'armor': 50}}


