ITEMS_ATTRIBUTES = {
    'dorans_blade': {'buffs': {},
                     'dmgs': {},
                     'general_attributes': {'castable': False},
                     'non_unique_stats': {'additive': {'ad': 7,
                                                       'hp': 70,
                                                       'lifesteal': 0.03}},
                     'unique_stats': {}},
    'hextech_gunblade': {'buffs': {'gunblade_slow': {'affected_stats': {'move_speed_reduction': 0.4},
                                                     'duration': 2,
                                                     'max_stacks': 1,
                                                     'on_hit': {'add_dmg': ['placeholder'],
                                                                'apply_buff': ['placeholder'],
                                                                'reduce_cd': {},
                                                                'remove_buff': ['placeholder']},
                                                     'target_type': 'enemy'}},
                         'dmgs': {'gunblade_dmg_0': {'delay': None,
                                                     'dmg_category': 'standard_dmg',
                                                     'dmg_source': 'gunblade',
                                                     'dmg_type': 'magic',
                                                     'dmg_values': 150,
                                                     'dot': False,
                                                     'life_conversion_type': 'spellvamp',
                                                     'max_targets': 1,
                                                     'mods': {'enemy': {},
                                                              'player': {'ap': 0.4}},
                                                     'radius': None,
                                                     'target_type': 'enemy',
                                                     'usual_max_targets': 1}},
                         'general_attributes': {'base_cd': 'placeholder',
                                                'cast_time': 0,
                                                'castable': True,
                                                'channel_time': None,
                                                'dashed_distance': None,
                                                'independent_cast': True,
                                                'move_while_casting': True,
                                                'range': 'placeholder',
                                                'resets_aa': False,
                                                'toggled': False,
                                                'travel_time': 0.25},
                         'non_unique_stats': {'additive': {'ad': 45,
                                                           'ap': 65,
                                                           'lifesteal': 0.12}},
                         'unique_stats': {'additive': {'ap': 150,
                                                       'move_speed': 150,
                                                       'spellvamp': 0.2}}}}

ITEMS_EFFECTS = {
    'dorans_blade': {'enemy': {'actives': {'buffs': ['gunblade_slow'],
                                           'dmg': ['gunblade_dmg_0'],
                                           'remove_buff': []},
                               'passives': {'buffs': [],
                                            'dmg': [],
                                            'remove_buff': []}},
                     'player': {'actives': {'buffs': [],
                                            'dmg': [],
                                            'remove_buff': []},
                                'passives': {'buffs': [],
                                             'dmg': [],
                                             'remove_buff': []}}},
    'hextech_gunblade': {'enemy': {'actives': {'buffs': ['gunblade_slow'],
                                               'dmg': ['gunblade_dmg_0'],
                                               'remove_buff': []},
                                   'passives': {'buffs': [],
                                                'dmg': [],
                                                'remove_buff': []}},
                         'player': {'actives': {'buffs': [],
                                                'dmg': [],
                                                'remove_buff': []},
                                    'passives': {'buffs': [],
                                                 'dmg': [],
                                                 'remove_buff': []}}}}

ITEMS_CONDITIONS = {}

