ITEMS_NON_UNIQUE_STATS_DCT = {
    'ABYSSAL_SCEPTER': {'ap': 70,
                        'mr': 50},
    'AEGIS_OF_THE_LEGION': {'hp': 200,
                            'mr': 20},
    'AETHER_WISP': {'ap': 30},
    'AMPLIFYING_TOME': {'ap': 20},
    'ANCIENT_COIN': {'mp': 0.25,
                     'mp5': 0.25},
    'ARCHANGELS_STAFF': {'ap': 60,
                         'mp': 0.5,
                         'mp5': 0.5},
    'ARDENT_CENSER': {'ap': 40,
                      'cdr': 0.1,
                      'mp': 1.0,
                      'mp5': 1.0},
    'ATHENES_UNHOLY_GRAIL': {'ap': 60,
                             'cdr': 0.2,
                             'mp': 0.5,
                             'mp5': 0.5,
                             'mr': 25},
    'AVARICE_BLADE': {'crit_chance': 0.1},
    'BANNER_OF_COMMAND': {'ap': 60,
                          'cdr': 0.1,
                          'hp': 200,
                          'mr': 20},
    'BANSHEES_VEIL': {'hp': 1.0,
                      'hp5': 1.0,
                      'mr': 55},
    'BERSERKERS_GREAVES': {'att_speed': 0.25},
    'BILGEWATER_CUTLASS': {'ad': 25,
                           'lifesteal': 0.08},
    'BLADE_OF_THE_RUINED_KING': {'ad': 25,
                                 'att_speed': 0.4,
                                 'lifesteal': 0.1},
    'BLASTING_WAND': {'ap': 40},
    'BOOTS_OF_MOBILITY': {},
    'BOOTS_OF_SPEED': {},
    'BOOTS_OF_SWIFTNESS': {},
    'BRAWLERS_GLOVES': {'crit_chance': 0.08},
    'B_F_SWORD': {'ad': 50},
    'CATALYST_THE_PROTECTOR': {'hp': 200,
                               'mp': 300},
    'CHAIN_VEST': {'armor': 40},
    'CHALICE_OF_HARMONY': {'mp': 0.5,
                           'mp5': 0.5,
                           'mr': 25},
    'CLOAK_OF_AGILITY': {'crit_chance': 0.15},
    'CLOTH_ARMOR': {'armor': 15},
    'CRYSTALLINE_BRACER': {'hp': 0.5,
                           'hp5': 0.5},
    'DAGGER': {'att_speed': 0.15},
    'DEATHFIRE_GRASP': {'ap': 120,
                        'cdr': 0.1},
    'DORANS_BLADE': {'ad': 7,
                     'hp': 70,
                     'lifesteal': 0.03},
    'DORANS_RING': {'ap': 15,
                    'hp': 60},
    'DORANS_SHIELD': {'hp': 80},
    'ENCHANTMENT_ALACRITY': {},
    'ENCHANTMENT_CAPTAIN': {},
    'ENCHANTMENT_DEVOURER': {'att_speed': 0.5},
    'ENCHANTMENT_DISTORTION': {},
    'ENCHANTMENT_FUROR': {},
    'ENCHANTMENT_HOMEGUARD': {},
    'ENCHANTMENT_JUGGERNAUT': {'cdr': 0.1,
                               'hp': 500},
    'ENCHANTMENT_MAGUS': {'ap': 80,
                          'cdr': 0.2},
    'ENCHANTMENT_WARRIOR': {'ad': 45,
                            'armor': 10,
                            'cdr': 0.1},
    'ESSENCE_REAVER': {'ad': 80,
                       'cdr': 0.1,
                       'lifesteal': 0.1},
    'FACE_OF_THE_MOUNTAIN': {'cdr': 0.1,
                             'hp': 1.0,
                             'hp5': 1.0},
    'FAERIE_CHARM': {'mp': 0.25,
                     'mp5': 0.25},
    'FIENDISH_CODEX': {'ap': 30},
    'FORBIDDEN_IDOL': {'mp': 0.5,
                       'mp5': 0.5},
    'FROSTFANG': {'ap': 10,
                  'mp': 0.5,
                  'mp5': 0.5},
    'FROST_QUEENS_CLAIM': {'ap': 50,
                           'cdr': 0.1,
                           'mp': 0.5,
                           'mp5': 0.5},
    'FROZEN_HEART': {'armor': 100,
                     'cdr': 0.2,
                     'mp': 400},
    'FROZEN_MALLET': {'ad': 30,
                      'hp': 700},
    'GIANTS_BELT': {'hp': 380},
    'GLACIAL_SHROUD': {'armor': 20,
                       'mp': 250},
    'GUARDIAN_ANGEL': {'armor': 50,
                       'mr': 50},
    'GUINSOOS_RAGEBLADE': {'ad': 30,
                           'ap': 40},
    'HAUNTING_GUISE': {'ap': 25,
                       'hp': 200},
    'HEXDRINKER': {'ad': 25,
                   'mr': 30},
    'HEXTECH_GUNBLADE': {'ad': 45,
                         'ap': 65,
                         'lifesteal': 0.12},
    'HEXTECH_REVOLVER': {'ap': 40},
    'HUNTERS_MACHETE': {},
    'ICEBORN_GAUNTLET': {'ap': 30,
                         'armor': 60,
                         'cdr': 0.1,
                         'mp': 500},
    'INFINITY_EDGE': {'ad': 80,
                      'crit_chance': 0.25},
    'IONIAN_BOOTS_OF_LUCIDITY': {},
    'KINDLEGEM': {'hp': 200},
    'LAST_WHISPER': {'ad': 40},
    'LIANDRYS_TORMENT': {'ap': 50,
                         'hp': 300},
    'LICH_BANE': {'ap': 80,
                  'move_speed': 0.05,
                  'mp': 250},
    'LOCKET_OF_THE_IRON_SOLARI': {'cdr': 0.1,
                                  'hp': 400,
                                  'mr': 20},
    'LONG_SWORD': {'ad': 10},
    'MADREDS_RAZORS': {'att_speed': 0.15},
    'MANAMUNE': {'ad': 25,
                 'mp': 0.25,
                 'mp5': 0.25},
    'MAW_OF_MALMORTIUS': {'ad': 60,
                          'mr': 40},
    'MEJAIS_SOULSTEALER': {'ap': 20},
    'MERCURIAL_SCIMITAR': {'ad': 80,
                           'mr': 35},
    'MERCURYS_TREADS': {'mr': 25},
    'MIKAELS_CRUCIBLE': {'cdr': 0.1,
                         'mp': 1.0,
                         'mp5': 1.0,
                         'mr': 40},
    'MORELLONOMICON': {'ap': 80,
                       'cdr': 0.2,
                       'mp': 1.0,
                       'mp5': 1.0},
    'NASHORS_TOOTH': {'ap': 60,
                      'att_speed': 0.5},
    'NEEDLESSLY_LARGE_ROD': {'ap': 80},
    'NEGATRON_CLOAK': {'mr': 45},
    'NINJA_TABI': {'armor': 25},
    'NOMADS_MEDALLION': {'hp': 0.25,
                         'hp5': 0.25,
                         'move_speed': 10,
                         'mp': 0.25,
                         'mp5': 0.25},
    'NULL_MAGIC_MANTLE': {'mr': 25},
    'OHMWRECKER': {'armor': 50,
                   'cdr': 0.1,
                   'hp': 1.0,
                   'hp5': 1.0},
    'PERFECT_HEX_CORE': {'ap': 60,
                         'ap_per_lvl': 6,
                         'mp': 500},
    'PHAGE': {'ad': 20,
              'hp': 200},
    'PHANTOM_DANCER': {'att_speed': 0.5,
                       'crit_chance': 0.3,
                       'move_speed': 0.05},
    'PICKAXE': {'ad': 25},
    'POACHERS_KNIFE': {},
    'QUICKSILVER_SASH': {'mr': 30},
    'RABADONS_DEATHCAP': {'ap': 120},
    'RANDUINS_OMEN': {'armor': 70,
                      'hp': 500},
    'RANGERS_TRAILBLAZER': {},
    'RAPTOR_CLOAK': {'armor': 30,
                     'hp': 1.0,
                     'hp5': 1.0},
    'RAVENOUS_HYDRA': {'ad': 75,
                       'hp': 1.0,
                       'hp5': 1.0,
                       'lifesteal': 0.12},
    'RECURVE_BOW': {'att_speed': 0.3},
    'REJUVENATION_BEAD': {'hp': 0.5,
                          'hp5': 0.5},
    'RELIC_SHIELD': {'hp': 75},
    'RIGHTEOUS_GLORY': {'hp': 1.0,
                        'hp5': 1.0,
                        'mp': 300},
    'ROD_OF_AGES': {'ap': 60,
                    'hp': 450,
                    'mp': 450},
    'RUBY_CRYSTAL': {'hp': 150},
    'RUBY_SIGHTSTONE': {'hp': 400},
    'RUNAANS_HURRICANE': {'att_speed': 0.7},
    'RYLAIS_CRYSTAL_SCEPTER': {'ap': 100,
                               'hp': 400},
    'SAPPHIRE_CRYSTAL': {'mp': 200},
    'SEEKERS_ARMGUARD': {'ap': 25,
                         'armor': 30},
    'SHEEN': {'ap': 25,
              'mp': 200},
    'SIGHTSTONE': {'hp': 150},
    'SKIRMISHERS_SABRE': {},
    'SORCERERS_SHOES': {'flat_magic_penetration': 15},
    'SPECTRES_COWL': {'hp': 200,
                      'mr': 35},
    'SPELLTHIEFS_EDGE': {'ap': 5,
                         'mp': 0.25,
                         'mp5': 0.25},
    'SPIRIT_VISAGE': {'cdr': 0.1,
                      'hp': 1.0,
                      'hp5': 1.0,
                      'mr': 55},
    'STALKERS_BLADE': {},
    'STATIKK_SHIV': {'att_speed': 0.4,
                     'crit_chance': 0.2,
                     'move_speed': 0.06},
    'STINGER': {'att_speed': 0.4},
    'SUNFIRE_CAPE': {'armor': 45,
                     'hp': 450},
    'SWORD_OF_THE_OCCULT': {'ad': 10},
    'TALISMAN_OF_ASCENSION': {'cdr': 0.1,
                              'hp': 1.0,
                              'hp5': 1.0,
                              'move_speed': 20,
                              'mp': 1.0,
                              'mp5': 1.0},
    'TARGONS_BRACE': {'hp': 0.5,
                      'hp5': 0.5},
    'TEAR_OF_THE_GODDESS': {'mp': 0.25,
                            'mp5': 0.25},
    'THE_BLACK_CLEAVER': {'ad': 50,
                          'cdr': 0.1,
                          'hp': 200},
    'THE_BLACK_SPEAR': {},
    'THE_BLOODTHIRSTER': {'ad': 80},
    'THE_BRUTALIZER': {'ad': 25},
    'THE_HEX_CORE_MK_1': {'ap': 20,
                          'ap_per_lvl': 4,
                          'mp': 150},
    'THE_HEX_CORE_MK_2': {'ap': 40,
                          'ap_per_lvl': 5,
                          'mp': 300},
    'THORNMAIL': {'armor': 100},
    'TIAMAT': {'ad': 40,
               'hp': 1.0,
               'hp5': 1.0},
    'TRINITY_FORCE': {'ad': 30,
                      'ap': 30,
                      'att_speed': 0.3,
                      'crit_chance': 0.1,
                      'hp': 250,
                      'move_speed': 0.08,
                      'mp': 200},
    'TWIN_SHADOWS': {'ap': 80,
                     'cdr': 0.1,
                     'move_speed': 0.06},
    'VAMPIRIC_SCEPTER': {'ad': 10,
                         'lifesteal': 0.08},
    'VOID_STAFF': {'ap': 70},
    'WARDENS_MAIL': {'armor': 45},
    'WARMOGS_ARMOR': {'hp': 800},
    'WILL_OF_THE_ANCIENTS': {'ap': 80,
                             'cdr': 0.1},
    'WITS_END': {'att_speed': 0.5,
                 'mr': 30},
    'WRIGGLES_LANTERN': {'ad': 12,
                         'att_speed': 0.3},
    'YOUMUUS_GHOSTBLADE': {'ad': 30,
                           'cdr': 0.1,
                           'crit_chance': 0.15},
    'ZEAL': {'att_speed': 0.2,
             'crit_chance': 0.1,
             'move_speed': 0.05},
    'ZEKES_HERALD': {'cdr': 0.2,
                     'hp': 250},
    'ZEPHYR': {'ad': 25,
               'att_speed': 0.5,
               'cdr': 0.1,
               'move_speed': 0.1},
    'ZHONYAS_HOURGLASS': {'ap': 120,
                          'armor': 50}}


